<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>launcherdotnet.Plugins.HelloWorld</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\launcherdotnet\launcherdotnet.csproj" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy &quot;$(TargetDir)$(TargetName).dll&quot; &quot;..\..\launcherdotnet\bin\$(Configuration)\net10.0-windows\plugins\$(TargetName)\&quot; /Y /I" />
	</Target>

</Project>
